### PR TITLE
added spec for multi network support; fixed minor typos;

### PR DESCRIPTION
**Pull request by awoie**
added support for multiple Ethereum networks; fixed minor typos;

### CODE REVIEW

**Comment by oed** [comment]
Why not use chainID instead of a string name? Seems like that would be more flexible. Checkout this list of chainids for different EVM networks: https://chainid.network/

**Comment by mirceanis** [comment]
I guess both options could work.
A usecase (although not really advisable) for using strings instead of chainID is the ability to have multiple registries in the same chain.

**Comment by awoie** [comment]
@oed @mirceanis is the short name in the registry unique? Another point why using the registry might not be enough is because we are going to support permissioned Quorum-based networks as well which might not be added to the registry. But a hybrid of short name + handling for such systems + handling for potential registries per network might work.

**Comment by oed** [comment]
@awoie The Quorum based networks still needs to have a unique chainId in order to prevent reply attacks as I mentioned yesterday. So even if they are not in the registry it should be fine. But I think you should investigate before you start maintaining your own separate registry for basically the same thing 🙂

**Comment by awoie** [comment]
@oed As far as I understood, just because there is a registry, nobody prevents a Quorum-based blockchain from using an already registered chainId, right? These are basically private networks.

**Comment by oed** [comment]
Yeah there isn't any enforcement. But if they did it's probably a really bad idea since it enables replay attacks. If they are not aware of this it's a real problem.

**Comment by awoie** [comment]
@oed I agree that this will be a good idea but there won't be a guarantee that private/permissioned networks, e.g., based on Quorum, will find its way into the registry. If they don't share any state with other networks such as the public Ethereum mainnet, then they could manage their replay protection internally within their consortium by allocating their own chain IDs, potentially having clashes with chainid.network. 

Anyways, it is not the intention of the did:ethr spec to come up with an exhaustive list of chain IDs. The did:ethr community/implementers of the spec will need to specify the target ERC1056 registry per network in the resolver implementation to allow others to resolve did:ethr: DIDs.

I'm in favour of the string notation because it is more verbose. It would be great if we could use "short name" (if unique) anyways for chainid.network chains, e.g., did:ethr:<short-name>:0xab. If we want to support multiple ERC1056 registries per network, then this could be done by amending the did:ethr by another discriminator, e.g., did:ethr:<short name>[-<discriminator>]. If a private/permissioned network ignores the registry, then we could just add another discriminator for chains outside of the chainid.network universe.

@oed @mirceanis thoughts?

**Comment by mirceanis** [comment]
The way I see it, these 2 methods of wrapping an address into a DID do not exclude each other, and this is more of a matter of configuration.
Using config of the resolver it is already possible to wrap an address into a DID on different chains and the sole purpose of this is to allow disambiguation.

The resolver will have to be configured with the proper RPC endpoint and registry address anyway and the mapping: `network name` -> (`rpc`, `registry`) can just as easily live next to `chainID` -> (`rpc`, `registry`)

**Comment by awoie** [comment]
@mirceanis @oed The did:ethr spec and the implementation (resolver) are different things. In theory, many did:ethr resolver implementations can exist but they all should be able to resolve the did to the same did document. I agree that we won't have to specify the RPC endpoint in the did:ethr spec but we will have to specify the ERC1056 registry address of the target network. Anyways, I believe it makes sense to have everything that is chainid.network related in the did:ethr implementation. I agree with the approach that an implementation will include a mapping from did:ethr:<network> to chainid.network entry. @oed From this perspective, I believe the current proposal in the PR is fine.

**Comment by ajunge** [comment]
So will we use "networkName" (alastria:telsius, ropsten, rinkeby, etc) or "chainId" (the ones provided from https://github.com/ethereum-lists/chains )

**Pull request merged**
